// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPFlUK2k4dZwi5AEMZpxNVGel55OuvjE',
    appId: '1:26245893659:web:8eba765a81d1d59a39f2be',
    messagingSenderId: '26245893659',
    projectId: 'cabougeou-d33a9',
    authDomain: 'cabougeou-d33a9.firebaseapp.com',
    storageBucket: 'cabougeou-d33a9.firebasestorage.app',
    measurementId: 'G-V7R1FHG6V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPv7ecpc6fwJII-NUiqCWuk-CXG-PoGZ4',
    appId: '1:26245893659:android:779ee767311c91aa39f2be',
    messagingSenderId: '26245893659',
    projectId: 'cabougeou-d33a9',
    storageBucket: 'cabougeou-d33a9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjSc2C002TwU38-uVYI8b6yvTUHTA5B5Q',
    appId: '1:26245893659:ios:f61bd67f92752e2a39f2be',
    messagingSenderId: '26245893659',
    projectId: 'cabougeou-d33a9',
    storageBucket: 'cabougeou-d33a9.firebasestorage.app',
    iosBundleId: 'com.example.mydefenseoff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdPFlUK2k4dZwi5AEMZpxNVGel55OuvjE',
    appId: '1:26245893659:web:04e8f50db469193339f2be',
    messagingSenderId: '26245893659',
    projectId: 'cabougeou-d33a9',
    authDomain: 'cabougeou-d33a9.firebaseapp.com',
    storageBucket: 'cabougeou-d33a9.firebasestorage.app',
    measurementId: 'G-ZNMVHEBMCS',
  );
}
